// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeek8.EF;

namespace TestWeek8.EF.Migrations
{
    [DbContext(typeof(RistoranteContext))]
    partial class RistoranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeek8.Core.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdMenu");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            IdMenu = 1,
                            Nome = "Menu giornaliero"
                        },
                        new
                        {
                            IdMenu = 2,
                            Nome = "Menu serale"
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Piatto", b =>
                {
                    b.Property<int>("IdPiatto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipologia")
                        .HasColumnType("int");

                    b.HasKey("IdPiatto");

                    b.HasIndex("MenuID");

                    b.ToTable("Piatti");

                    b.HasData(
                        new
                        {
                            IdPiatto = 1,
                            Descrizione = "piatto di tagliatelle al ragu di carne, 100g",
                            MenuID = 1,
                            Nome = "Tagliatelle al Ragu",
                            Prezzo = 12.55m,
                            Tipologia = 0
                        },
                        new
                        {
                            IdPiatto = 2,
                            Descrizione = "selezione di verdure miste",
                            MenuID = 1,
                            Nome = "Verdure miste",
                            Prezzo = 12.55m,
                            Tipologia = 2
                        },
                        new
                        {
                            IdPiatto = 3,
                            Descrizione = "brodo di carne di manzo ",
                            MenuID = 2,
                            Nome = "Brodo di carne",
                            Prezzo = 12.55m,
                            Tipologia = 0
                        },
                        new
                        {
                            IdPiatto = 4,
                            Descrizione = "cotoletta alla milanese",
                            MenuID = 2,
                            Nome = "Cotoletta",
                            Prezzo = 12.55m,
                            Tipologia = 1
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Utente", b =>
                {
                    b.Property<int>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdUtente");

                    b.ToTable("Utenti");

                    b.HasData(
                        new
                        {
                            IdUtente = 1,
                            Email = "Giovanni.Storti@gmail.com",
                            Password = "pdor",
                            Tipo = 0
                        },
                        new
                        {
                            IdUtente = 2,
                            Email = "Giacomino.Poretti@gmail.com",
                            Password = "tafazzi",
                            Tipo = 1
                        },
                        new
                        {
                            IdUtente = 3,
                            Email = "Aldo.Baglio@gmail.com",
                            Password = "rolando",
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Piatto", b =>
                {
                    b.HasOne("TestWeek8.Core.Models.Menu", "menuAppartenenza")
                        .WithMany("Piatti")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
